---
- name: Install Nginx On WebServers
  hosts: pub
  gather_facts: yes
  become: yes
  become_user: root
  tags: nginx
  tasks:
  - name: Perform apt update
    shell: apt-get update
    tags: [apt, update]

  - name: Install Nginx
    shell: apt-get install -y nginx
    tags: [nginx, install]

  - name: Start Nginx Server
    # service: name=nginx state=started enabled=yes
    shell: service nginx start && systemctl enable nginx
    tags: [nginx, start]
    
- name: Install Base Tools
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tags: basetools
  tasks:
  - name: Perform apt update
    shell: apt-get update
  - name: Install Base Tools
    apt: name={{ item }} state=present
    with_items:
      - unzip
      - certbot
      - net-tools
      - jq

- name: Copy application file
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: Perform copying files
    copy:
      src: "{{ item }}"
      dest: /var/www/html/{{ item }}
      owner: root
      group: root
      mode: '0644'
    with_items:
      - contact.html
      - orders.html
      - aboutus.html
